name: Run migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Run Migrations
        run: pnpm migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TOKEN: ${{ secrets.DATABASE_TOKEN }}

      - name: Run migrations
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
